### ISSUE TITLE
Shift in location between EVI and NDVI

### ISSUE THREAD

**Issue by simgislab** [nextgis/dhi#5]

**Comment by amuriy** [comment]
Shift in location between EVI and NDVI not found.

**Comment by simgislab** [comment]
there is actually a difference, if you compare between two final DHIs in WGS84, but there is none in SIN

try reprojecting them again with

``````
gdalwarp -t_srs "EPSG:4326" -tr 0.0083 0.0083 dhi_ndviqa_f.tif ..\dhi_ndviqa_f2.tif```
``````

**Comment by amuriy** [comment]
It was bug in GRASS location, in which DHI's were computed. EVI and NDVI mapsets were computed in different projections (lat/long and sinusoidal), but in the same units (meters). 
Now projection of the whole location changed to sinusoidal, DHI NDVI was recomputed and transformed to WGS84.

**Comment by simgislab** [comment]
DHI of FPAR, LAI, EVI, NDVI should all match

NDVI used to aligh with FPAR/LAI, now it doesn't. But it does align with EVI.

**Comment by amuriy** [comment]
Done
