### ISSUE TITLE
Check if LADSWEB data is the same with Data pool

### ISSUE THREAD

**Issue by simgislab** [nextgis/dhi#7]
http://e4ftl01.cr.usgs.gov/MOTA/MCD15A2.005/

and 

ftp://ladsweb.nascom.nasa.gov/allData/5/MCD15A2/2015/

**Comment by amuriy** [comment]
HDF's in two archives are identical. Tested with gdalinfo  + diff and with QGIS.

**Comment by simgislab** [comment]
good, added info to the docs https://github.com/nextgis/dhi/wiki/Process
